### ISSUE TITLE
error: value addPlugins is not a member of sbt.Project on first build

### ISSUE THREAD

**Issue by tomwilderspin** [typesafehub/activator-hello-play-2_3-scala#3]
Hi,
Ive been trying to build this project using activator and have come up against this error: 
error: value addPlugins is not a member of sbt.Project. The issue looks to be down a line in the build.sbt file, removing the following line allows the project to build.

~/first-play/build.sbt:11: error: value addPlugins is not a member of sbt.Project
lazy val root = (project in file(".")).addPlugins(PlayScala)

Checking the sbt > about option this looks to be the correct 0.13.5-M2 version so I'm not sure why addProjects is missing??

This is my first go at activator, sbt, and play so this might be a rookie mistake on my part, but any pointers on solving this would be great!

**Comment by tomwilderspin** [comment]
Closing this as testing with other play framework based templates the issue still occurs, looks to be an issue with SBT itself (maybe sub-project related).

Will try with a clean install see if the error shows up again.

**Comment by ignaciomosca** [comment]
I'm experiencing this issue too. Did a clean install solved it for you @tomwilderspin ?

**Comment by tomwilderspin** [comment]
@ignaciomosca yeah solved it for me. I had an old version of SBT which the activator was looking at which caused the error. Ran the same on a clean install and no problems :)

**Comment by ignaciomosca** [comment]
Yeah, one of the problems I've been having with some Activator templates are related to the fact that if  you don't have the exact same version of sbt and scala, it won't compile
